### ISSUE TITLE
fix npm for development

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-morph#579]
I'm working with latests npm, node, tsc and some tests are failing. 

Seems to be related with manipulation settings `insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces` and an old commend you made in breaking-changes.md: 

> ### Imports Formatting
> Instead of being written as:
> ```ts
> import {SomeExport} from "./SomeFile";
> ```
> Imports will now be written with spaces (as is the default in the compiler):
> ```ts
> import { SomeExport } from "./SomeFile";
> ```
> If you don't want this behaviour, then set the `insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces` to `false` in the [manipulation settings](https://dsherret.github.io/ts-morph/manipulation/settings).

I could fix the error but probably not eleganly. and forcing that configuration where is needed (and you probably will reject the PR). I  really would like to work on this project using npm  and I feel we are so close to it , perhaps seeing at the errors you have a clue where the problem is?

Seems that when inserting functions and methods in BodyableNode, StatementedNode or similar, the first brace is missing a space, just like you said in the comment. That only happen for function-like inserted statements, other nodes that have similar brace are printed fine.

Just 9 errors, would be awesome if you can give me a tip where should I configure insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces or where to force the missing space like with writer.space() - I'm seeing that in printers that work OK this is present:

```
if (formatSettings.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces && !StringUtils.startsWithNewLine(specifierText))
            writer.space();
        writer.write(specifierText);
```
but not in src/structurePrinters/function/FunctionDeclarationStructurePrinter.ts - could be that? 

Thanks
```
> ts-morph@1.3.0 test /home/sg/git/ts-morph
> cross-env TS_NODE_COMPILER="ttypescript" TS_NODE_TRANSPILE_ONLY="true" mocha --opts mocha.opts --grep @performance --invert


TypeScript version: 3.3.1

  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  4140 passing (12s)
  2 pending
  9 failing

  1) BodyableNode
       setBodyText
         class method
           should add a body if none exists:

      AssertionError: expected 'declare class C {\n    myMethod(){\n        var myVar;\n    }\n}' to equal 'declare class C {\n    myMethod() {\n        var myVar;\n    }\n}'
      + expected - actual

       declare class C {
      -    myMethod(){
      +    myMethod() {
               var myVar;
           }
       }
      
      at doTest (src/tests/compiler/ast/base/bodyableNodeTests.ts:37:53)
      at Context.<anonymous> (src/tests/compiler/ast/base/bodyableNodeTests.ts:47:17)

  2) BodyableNode
       setBodyText
         function
           should set the body text when not exists:

      AssertionError: expected 'function myFunction(){\n    var myVar;\n}' to equal 'function myFunction() {\n    var myVar;\n}'
      + expected - actual

      -function myFunction(){
      +function myFunction() {
           var myVar;
       }
      
      at doTest (src/tests/compiler/ast/base/bodyableNodeTests.ts:57:53)
      at Context.<anonymous> (src/tests/compiler/ast/base/bodyableNodeTests.ts:77:17)

  3) BodyableNode
       addBody
         should add the function body when it doesn't exist and has a type:

      AssertionError: expected 'function myFunction(): string{\n}' to equal 'function myFunction(): string {\n}'
      + expected - actual

      -function myFunction(): string{
      +function myFunction(): string {
       }
      
      at doTest (src/tests/compiler/ast/base/bodyableNodeTests.ts:138:49)
      at Context.<anonymous> (src/tests/compiler/ast/base/bodyableNodeTests.ts:146:13)

  4) BodyableNode
       addBody
         should add the function body when it doesn't exist:

      AssertionError: expected 'function myFunction(){\n}' to equal 'function myFunction() {\n}'
      + expected - actual

      -function myFunction(){
      +function myFunction() {
       }
      
      at doTest (src/tests/compiler/ast/base/bodyableNodeTests.ts:138:49)
      at Context.<anonymous> (src/tests/compiler/ast/base/bodyableNodeTests.ts:150:13)

  5) BodyableNode
       addBody
         should add the function body when it doesn't exist and has no semicolon:

      AssertionError: expected 'function myFunction(){\n}' to equal 'function myFunction() {\n}'
      + expected - actual

      -function myFunction(){
      +function myFunction() {
       }
      
      at doTest (src/tests/compiler/ast/base/bodyableNodeTests.ts:138:49)
      at Context.<anonymous> (src/tests/compiler/ast/base/bodyableNodeTests.ts:154:13)

  6) GetAccessorDeclaration
       set
         should modify when changed:

      AssertionError: expected '\nclass Identifier {\n    /**\n     * d\n     */\n    @dec\n    public abstract static get asdf<T>(p): string{\n        class C {\n        }\n\n        enum E {\n        }\n\n        function F() {\n        }\n\n        interface I {\n        }\n\n        namespace N {\n        }\n\n        type T = string;\n\n        console;\n    }\n}\n' to equal '\nclass Identifier {\n    /**\n     * d\n     */\n    @dec\n    public abstract static get asdf<T>(p): string {\n        class C {\n        }\n\n        enum E {\n        }\n\n        function F() {\n        }\n\n        interface I {\n        }\n\n        namespace N {\n        }\n\n        type T = string;\n\n        console;\n    }\n}\n'
      + expected - actual

           /**
            * d
            */
           @dec
      -    public abstract static get asdf<T>(p): string{
      +    public abstract static get asdf<T>(p): string {
               class C {
               }
       
               enum E {
      
      at doTest (src/tests/compiler/ast/class/getAccessorDeclarationTests.ts:79:49)
      at Context.<anonymous> (src/tests/compiler/ast/class/getAccessorDeclarationTests.ts:135:13)

  7) SetAccessorDeclaration
       set
         should modify when changed:

      AssertionError: expected '\nclass Identifier {\n    /**\n     * d\n     */\n    @dec\n    public abstract static set asdf<T>(p): string{\n        class C {\n        }\n\n        enum E {\n        }\n\n        function F() {\n        }\n\n        interface I {\n        }\n\n        namespace N {\n        }\n\n        type T = string;\n\n        console;\n    }\n}\n' to equal '\nclass Identifier {\n    /**\n     * d\n     */\n    @dec\n    public abstract static set asdf<T>(p): string {\n        class C {\n        }\n\n        enum E {\n        }\n\n        function F() {\n        }\n\n        interface I {\n        }\n\n        namespace N {\n        }\n\n        type T = string;\n\n        console;\n    }\n}\n'
      + expected - actual

           /**
            * d
            */
           @dec
      -    public abstract static set asdf<T>(p): string{
      +    public abstract static set asdf<T>(p): string {
               class C {
               }
       
               enum E {
      
      at doTest (src/tests/compiler/ast/class/setAccessorDeclarationTests.ts:79:49)
      at Context.<anonymous> (src/tests/compiler/ast/class/setAccessorDeclarationTests.ts:135:13)

  8) StatementedNode
       insertClasses
         should insert into a function with no body:

      AssertionError: expected 'function test(){\n    class C {\n    }\n}' to equal 'function test() {\n    class C {\n    }\n}'
      + expected - actual

      -function test(){
      +function test() {
           class C {
           }
       }
      
      at doFunctionTest (src/tests/compiler/ast/statement/statementedNode/classTests.ts:94:49)
      at Context.<anonymous> (src/tests/compiler/ast/statement/statementedNode/classTests.ts:98:13)

  9) StatementedNode
       insertStatements
         should insert statements into a function with no body:

      AssertionError: expected 'function i(){\n    statement;\n}\n' to equal 'function i() {\n    statement;\n}\n'
      + expected - actual

      -function i(){
      +function i() {
           statement;
       }
      
      at doFirstChildTest (src/tests/compiler/ast/statement/statementedNodeTests.ts:161:49)
      at Context.<anonymous> (src/tests/compiler/ast/statement/statementedNodeTests.ts:165:13)



npm ERR! Test failed.  See above for more details.

```

**Comment by dsherret** [comment]
Looks like I just forgot to push master (just did now so it should be fixed), but I recommend always doing development on the `dev` branch. For example, at the current moment there's been many changes in there.

**Comment by cancerberoSgx** [comment]
aja, thanks! will do currently with a very limited connection, that's also why I prefer npm, thanks
