### ISSUE TITLE
.findReferences() crash with allowSyntheticDefaultImports + ExportAssignment

### ISSUE THREAD

**Issue by osyrisrblx** [dsherret/ts-morph#650]
**Describe the bug**
Calling `.findReferences()` on a default import Identifier node which comes from an `ExportAssignment` node where the expression is an object causes a crash.

Seems to only happen with `allowSyntheticDefaultImports` set to `true`

Version: 2.3.0

**To Reproduce**

```ts
import { Project, ts } from "ts-morph";

console.log(ts.version); // 3.5.2

const project = new Project({ compilerOptions: { allowSyntheticDefaultImports: true } });
const a = project.createSourceFile("a.ts", `export = { x: 1 } as {};`);
const b = project.createSourceFile("b.ts", `import x from "./a";`);

b.getImportDeclarations()[0]
	.getDefaultImportOrThrow()
	.findReferences();
```

![image](https://user-images.githubusercontent.com/9200592/59815738-6102c300-92ce-11e9-8e90-d3891040239c.png)

**Expected behavior**

It should not crash.

**Comment by osyrisrblx** [comment]
This might be a TypeScript compiler bug, but I wasn't sure.

**Comment by dsherret** [comment]
Hey @osyrisrblx, yeah, I think this might be a bug in the compiler. I'm able to reproduce this in vscode (this is the tsserver log):

```
Info 85   [10:0:22.165] request:
    {"seq":9,"type":"request","command":"getApplicableRefactors","arguments":{"file":"c:/delete-me/src/b.ts","startLine":2,"startOffset":10,"endLine":2,"endOffset":10}}
Perf 86   [10:0:22.215] 9::getApplicableRefactors: elapsed time (in milliseconds) 49.8422
Info 87   [10:0:22.215] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":9,"success":true,"body":[]}
Info 88   [10:0:22.215] request:
    {"seq":10,"type":"request","command":"getCodeFixes","arguments":{"file":"c:/delete-me/src/b.ts","startLine":2,"startOffset":1,"endLine":2,"endOffset":24,"errorCodes":[6133]}}
Perf 89   [10:0:22.220] 10::getCodeFixes: elapsed time (in milliseconds) 4.4894
Info 90   [10:0:22.220] response:
    {"seq":0,"type":"response","command":"getCodeFixes","request_seq":10,"success":true,"body":[{"fixName":"unusedIdentifier","description":"Remove import from './a'","changes":[{"fileName":"c:/delete-me/src/b.ts","textChanges":[{"start":{"line":2,"offset":1},"end":{"line":2,"offset":26},"newText":""}]}],"fixId":"unusedIdentifier_delete","fixAllDescription":"Delete all unused declarations"}]}
Info 91   [10:0:22.836] request:
    {"seq":11,"type":"request","command":"references","arguments":{"file":"c:/delete-me/src/b.ts","line":2,"offset":10}}
Err 92    [10:0:22.840] Exception on executing command {"seq":11,"type":"request","command":"references","arguments":{"file":"c:/delete-me/src/b.ts","line":2,"offset":10}}:

    Debug Failure.

    Error: Debug Failure.
        at Object.assertDefined (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:2080:24)
        at getExportEqualsLocalSymbol (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:102364:33)
        at getImport (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:102338:38)
        at Object.getImportOrExportSymbol (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:102250:68)
        at getImportOrExportReferences (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103545:56)
        at getReferencesAtLocation (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103477:17)
        at getReferencesInContainer (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:103421:21)
        at getReferencesInContainerOrFiles (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:102983:21)
        at getReferencedSymbolsForSymbol (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:102974:21)
        at Object.getReferencedSymbolsForNode (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:102788:34)
        at Object.findReferencedSymbols (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:102474:60)
        at Object.findReferences (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:122217:41)
        at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129810:68
        at callbackProjectAndLocation (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129865:13)
        at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129838:24
        at forEachProjectInProjects (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129820:17)
        at combineProjectOutputWorker (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129835:13)
        at combineProjectOutputForReferences (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:129792:13)
        at IOSession.Session.getReferences (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130896:34)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:130001:61)
        at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131637:88
        at IOSession.Session.executeWithRequestId (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131628:28)
        at IOSession.Session.executeCommand (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131637:33)
        at IOSession.Session.onMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:131659:35)
        at Interface.<anonymous> (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js:132950:27)
        at Interface.emit (events.js:182:13)
        at Interface._onLine (readline.js:290:10)
        at Interface._normalWrite (readline.js:433:12)
        at Socket.ondata (readline.js:149:10)
        at Socket.emit (events.js:182:13)
        at addChunk (_stream_readable.js:279:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Socket.Readable.push (_stream_readable.js:219:10)
        at Pipe.onread (net.js:636:20)

File text of c:/delete-me/src/b.ts:
    import x from "./a";
    import test from "./a";
    

Info 93   [10:0:22.840] response:
    {"seq":0,"type":"response","command":"references","request_seq":11,"success":false,"message":"Error processing request. Debug Failure.\nError: Debug Failure.\n    at Object.assertDefined (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:2080:24)\n    at getExportEqualsLocalSymbol (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:102364:33)\n    at getImport (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:102338:38)\n    at Object.getImportOrExportSymbol (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:102250:68)\n    at getImportOrExportReferences (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:103545:56)\n    at getReferencesAtLocation (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:103477:17)\n    at getReferencesInContainer (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:103421:21)\n    at getReferencesInContainerOrFiles (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:102983:21)\n    at getReferencedSymbolsForSymbol (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:102974:21)\n    at Object.getReferencedSymbolsForNode (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:102788:34)\n    at Object.findReferencedSymbols (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:102474:60)\n    at Object.findReferences (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:122217:41)\n    at c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:129810:68\n    at callbackProjectAndLocation (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:129865:13)\n    at c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:129838:24\n    at forEachProjectInProjects (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:129820:17)\n    at combineProjectOutputWorker (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:129835:13)\n    at combineProjectOutputForReferences (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:129792:13)\n    at IOSession.Session.getReferences (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:130896:34)\n    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:130001:61)\n    at c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:131637:88\n    at IOSession.Session.executeWithRequestId (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:131628:28)\n    at IOSession.Session.executeCommand (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:131637:33)\n    at IOSession.Session.onMessage (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:131659:35)\n    at Interface.<anonymous> (c:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\node_modules\\typescript\\lib\\tsserver.js:132950:27)\n    at Interface.emit (events.js:182:13)\n    at Interface._onLine (readline.js:290:10)\n    at Interface._normalWrite (readline.js:433:12)\n    at Socket.ondata (readline.js:149:10)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:279:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at Pipe.onread (net.js:636:20)"}
Info 94   [10:0:24.59] request:
    {"seq":12,"type":"request","command":"definitionAndBoundSpan","arguments":{"file":"c:/delete-me/src/b.ts","line":2,"offset":10}}
Perf 95   [10:0:24.63] 12::definitionAndBoundSpan: elapsed time (in milliseconds) 4.1447
Info 96   [10:0:24.63] response:
    {"seq":0,"type":"response","command":"definitionAndBoundSpan","request_seq":12,"success":true,"body":{"definitions":[{"file":"c:/delete-me/src/a.ts","start":{"line":1,"offset":1},"end":{"line":1,"offset":25}}],"textSpan":{"start":{"line":2,"offset":8},"end":{"line":2,"offset":12}}}}
```

I believe it's this issue: https://github.com/microsoft/TypeScript/issues/27635

**Comment by Validark** [comment]
Now that I consider it, it's kinda funny that I ran into this and we found this bug. I wasn't even looking for trouble either; I'm just a troublesome TS-writer.

**Comment by osyrisrblx** [comment]
Closing this since the upstream issue seems to be resolved
