### ISSUE TITLE
getDefinitionNodes and findReferences crashes

### ISSUE THREAD

**Issue by elizabethdinella** [dsherret/ts-morph#693]
Hello,

I would like to traverse an AST and find all uses of all identifiers. However, calling the getDefinitionNodes() function causes a crash:

```javascript
const tsMorph = require("ts-morph");
const ts = tsMorph.ts;
const project = new tsMorph.Project();
const sourceFile = project.addExistingSourceFile("/home/edinella/gh-crawler/data/10-02-2018:23/2754/0RangeWithValue_buggy.js");

function visit(node){
        if(node.getKind() === ts.SyntaxKind.Identifier){
                let refs = node.getDefinitionNodes();  //this line causes the crash
                console.log(node.getText(), refs);
                console.log(node.getText()); //works with no issues 
        }
}

sourceFile.forEachDescendant(node => visit(node))
```
The error is as follows:
```
/home/edinella/node_modules/typescript/lib/typescript.js:125597
                throw error;
                ^

Error: Could not find source file: '/home/edinella/gh-crawler/data/10-02-2018:23/2754/0RangeWithValue_buggy.js'.
    at getValidSourceFile (/home/edinella/node_modules/typescript/lib/typescript.js:125593:29)
    at Object.getDefinitionAtPosition (/home/edinella/node_modules/typescript/lib/typescript.js:125904:71)
    at LanguageService.getDefinitionsAtPosition (/home/edinella/node_modules/ts-morph/dist/compiler/tools/LanguageService.js:118:45)
    at LanguageService.getDefinitions (/home/edinella/node_modules/ts-morph/dist/compiler/tools/LanguageService.js:110:21)
    at Identifier.getDefinitions (/home/edinella/node_modules/ts-morph/dist/compiler/ast/common/Identifier.js:25:46)
    at Identifier.getDefinitionNodes (/home/edinella/node_modules/ts-morph/dist/compiler/ast/common/Identifier.js:18:21)
    at visit (/home/edinella/find_all_ref.js:9:19)
    at sourceFile.forEachDescendant.node (/home/edinella/find_all_ref.js:14:38)
    at nodeCallback (/home/edinella/node_modules/ts-morph/dist/compiler/ast/common/Node.js:450:33)
    at node.forEachChild.innerNode (/home/edinella/node_modules/ts-morph/dist/compiler/ast/common/Node.js:485:37)
```

The file does exist, and just printing the identifier names works fine. Am I using the methods incorrectly?

**Comment by elizabethdinella** [comment]
Figured it out: I needed to add the allowJs compiler option!

**Comment by dsherret** [comment]
Hey @elizabethdinella, thanks for opening this and then coming back once you figured out the solution. I opened #694 to explore ways of improving the error message here.
