### ISSUE TITLE
Directory not found error when adding source file to node_modules folder with in memory file system

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-morph#830]
Doing this...

```ts
import { Project, ts } from "ts-morph";

// setup
const project = new Project({ useInMemoryFileSystem: true });
project.createSourceFile("/node_modules/@types/node/path.d.ts", `
declare module 'path' {
    namespace path {
        interface ParsedPath {}
        interface FormatInputPathObject {}
        interface PlatformPath {
            normalize(p: string): string;
            join(...paths: string[]): string;
            // other...
        }
    }
    const path: path.PlatformPath;
    export = path;
}`);
const sourceFile = project.createSourceFile("file.ts", `
import path from "path";
`);

for (const importDeclaration of sourceFile.getImportDeclarations()) {
  const moduleSpecifierSymbol = importDeclaration.getModuleSpecifier().getSymbolOrThrow();
  for (const symbol of moduleSpecifierSymbol.getExports()) {
    console.log(symbol.getName());
  }
}
```

Leads to:

```
Error: Directory not found: /node_modules/@types
    at InMemoryFileSystemHost.readDirSync (V:\test\node_modules\@ts-morph\common\dist\ts-morph-common.js:1830:19)
    at TransactionalFileSystem.readDirSync (V:\test\node_modules\@ts-morph\common\dist\ts-morph-common.js:1583:58)
    at TransactionalFileSystem.getDirectories (V:\test\node_modules\@ts-morph\common\dist\ts-morph-common.js:1615:21)
    at Object.getDirectories (V:\test\node_modules\@ts-morph\common\dist\ts-morph-common.js:2054:59)
    at Object.getAutomaticTypeDirectiveNames (V:\test\node_modules\typescript\lib\typescript.js:29701:52)
    at Object.createProgram (V:\test\node_modules\typescript\lib\typescript.js:100141:56)
    at Program._getOrCreateCompilerObject (V:\test\node_modules\ts-morph\dist\ts-morph.js:16710:57)
    at Program.get compilerObject [as compilerObject] (V:\test\node_modules\ts-morph\dist\ts-morph.js:16701:21)
    at TypeChecker._getCompilerObject (V:\test\node_modules\ts-morph\dist\ts-morph.js:16719:45)
    at TypeChecker.get compilerObject [as compilerObject] (V:\test\node_modules\ts-morph\dist\ts-morph.js:16599:21)
```

**Comment by cogwirrel** [comment]
Hey @dsherret!

Awesome library btw! 😄 

I just hit this issue - I wonder if you have a workaround at all?

Or perhaps I'm not using the library the right way...

I'm writing some unit tests that verify some generated code compiles. That generated code can have dependencies, and so I'm copying those dependencies into the in-memory filesystem's node_modules :) This works fine until I copy any `@types/*` dependencies, where I hit this issue.

The relevant code is [here](https://github.com/awslabs/nx-plugin-for-aws/blob/4a4ad0bccac344029ec1de15f15a20c81c9c1f51/packages/nx-plugin/src/open-api/ts-client/generator.utils.spec.ts) if useful - I've updated `resolveDependencyPath` to also resolve `@types/*` dependencies and that's when I hit this issue.

Perhaps there's a simpler way I'm missing to use the in-memory filesystem but allow particular dependencies to be resolved?

Cheers,
Jack

**Comment by cogwirrel** [comment]
Workaround found a few minutes later! Seems as though if I nest everything (`node_modules` and all the source files) under another folder it works as expected :)

**Comment by gwillen** [comment]
I am hitting the same thing -- I think what's happening is, there is special magic handling of directories that are type roots, in the in-memory filesystem, which disalllows using createSourceFile to put things there. I'm having trouble figuring out what the correct way is to do this.

**Comment by gwillen** [comment]
@cogwirrel FYI, a fix that seems to work is to call `saveSync` on your files after creating them, to "save" them to the in-memory filesystem. The impression I'm getting is that regular source files are read from some cache which is automatically populated by createSourceFile, but type definition files are read from "the real [virtual] filesystem", so if you don't save the files, they only exist for some purposes but not others. Calling `.saveSync` on the result of `.createSourceFile` (at least for each type definition file) solved this for me. (This required switching from `@ts-morph/bootstrap` to full `ts-morph`, in my case.)

So I guess it's sort of the opposite of my theory above -- it's not that writing to type roots is magic, it's that reading from type roots is _not_ magic (and reading regular source files is.)

**Comment by gwillen** [comment]
Note that "when adding source file to node_modules folder" is not strictly correct -- the crash doesn't happen when adding the file, it happens at the point where the compiler in `createProgram` goes to load the type definitions. I guess it's a bit weird that the compiler "knows", at this stage, that the created file exists, but is then unable to actually read it.

Curiously, it doesn't seem to be necessary to actually `.saveSync` the type definition file I'm actually using, to make the error go away (at least for now) -- it's sufficient to call it on any file inside the `@types` directory, to force it to be created, and then the compiler stops complaining. So it really seems like there's something inconsistent happening inside the compiler's treatment of the in-memory filesystem.
