### ISSUE TITLE
TypeError: Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by gdavidkov** [dsherret/ts-morph#874]
Hi,
I encountered the following error and I don't how to fix it.

TypeError: Cannot read property 'flags' of undefined

Version: 6.0.2 and 8.1.1

 TypeError: Cannot read property 'flags' of undefined
    at Object.getCheckFlags (C:\generate-docs\node_modules\@ts-morph\common\node_modules\typescript\lib\typescript.js:17530:23)
    at getTypeOfSymbol (C:\generate-docs\node_modules\@ts-morph\common\node_modules\typescript\lib\typescript.js:50065:33)
    at getTypeOfNode (C:\generate-docs\node_modules\@ts-morph\common\node_modules\typescript\lib\typescript.js:75770:24)
    at Object.getTypeAtLocation (C:\generate-docs\node_modules\@ts-morph\common\node_modules\typescript\lib\typescript.js:42671:31)
    at TypeChecker.getTypeAtLocation (C:\generate-docs\node_modules\ts-morph\dist\ts-morph.js:16639:74)
    at FunctionDeclaration.getType (C:\generate-docs\node_modules\ts-morph\dist\ts-morph.js:3064:42)
    at C:\generate-docs\dist\reference\main.js:153:37
    at Array.forEach (<anonymous>)
    at prepareNamespaces (C:\generate-docs\dist\reference\main.js:151:23)
    at Object.default_1 [as default] (C:\generate-docs\dist\reference\main.js:68:11)

**Comment by dsherret** [comment]
Closing for now. Please reopen once you have details.

**Comment by OmarOmeiri** [comment]
Hey @dsherret, before anything, I'd like to congratulate you for the attention you give to your users. Not many project maintainers are so attentive. 
Getting that out of the way, I had the same issue while running a simple test. I'm writing a visitor to auto generate documentations for my code. 

The single file I'm visiting: `MyClass.ts`

```ts
import type { LeanDocument } from 'mongoose';
import ReachDB from '../../Data/DataAccess';
import { Stock } from '../../Data/models/Stock';
import {
  IDocStock,
} from '../../Data/Typings/stock';

export class SomeClass {
  static async myMethod(
    ...someArgs: any[]
  ): Promise<[] | LeanDocument<IDocStock>[]> {
    const DB = new ReachDB(Stock);
    return DB.find(someArgs);
  }
}
```


```ts
import {
  Project,
  ts,
  Node,
} from 'ts-morph';

const PATH: string = process.env.LULLOPATH as string;

const files = [
  `${PATH}/backend/src/utils/TSC/MyClass.ts`,
];

function generateDocumentation(
  proj: Project,
): void {
  // Build a program using the set of root file names in fileNames
  const sourceFiles = proj.getSourceFiles();
  sourceFiles
    .forEach((file) => {
      if (file && !file.isDeclarationFile()) {
        file.forEachDescendant((node) => {
          console.log('############ ###############');
          console.log('Text:\n ', node.getText(), '\n');
          console.log(node.getType());
        });
      }
    });
}

const compilerOptions = {
  target: ts.ScriptTarget.ESNext,
  module: ts.ModuleKind.CommonJS,
  lib: [
    'lib.esnext.d.ts',
    'lib.dom.d.ts',
  ],
  allowJs: false,
  sourceMap: true,
  rootDir: './',
  composite: false,
  noEmit: true,
  noEmitOnError: true,
  resolveJsonModule: true,
  strict: true,
  noImplicitAny: true,
  strictNullChecks: true,
  strictFunctionTypes: true,
  strictBindCallApply: true,
  strictPropertyInitialization: true,
  noImplicitThis: true,
  alwaysStrict: true,
  noErrorTruncation: true,
  noFallthroughCasesInSwitch: true,
  moduleResolution: ts.ModuleResolutionKind.NodeJs,
  baseUrl: `${PATH}/backend`,
  types: ['node', 'express'],
  allowSyntheticDefaultImports: true,
  esModuleInterop: true,
  inlineSources: true,
  experimentalDecorators: true,
  emitDecoratorMetadata: true,
  skipLibCheck: true,
  forceConsistentCasingInFileNames: true,
};

const proj = new Project({ compilerOptions });
proj.addSourceFilesAtPaths(files);

generateDocumentation(proj);
```

The output of the script is:

```sh
############ ###############
Text:
  import type { LeanDocument } from 'mongoose';

Type {
  ... Bunch of Type stuff,
    flags: 1,
    id: 4,
    intrinsicName: 'error',
    objectFlags: 0
  }
}

############ ###############
Text:
  type { LeanDocument }

E:\Documents\CODE\WebDev\Lullo\backend\node_modules\@ts-morph\common\dist\typescript.js:54921
            if (symbol.flags & (32 /* Class */ | 64 /* Interface */)) {
                       ^
TypeError: Cannot read property 'flags' of undefined
    at tryGetDeclaredTypeOfSymbol (E:\Documents\CODE\WebDev\Lullo\backend\node_modules\@ts-morph\common\dist\typescript.js:54921:24)
    at getDeclaredTypeOfSymbol (E:\Documents\CODE\WebDev\Lullo\backend\node_modules\@ts-morph\common\dist\typescript.js:54918:20)
    at getTypeOfNode (E:\Documents\CODE\WebDev\Lullo\backend\node_modules\@ts-morph\common\dist\typescript.js:82477:24)
    at Object.getTypeAtLocation (E:\Documents\CODE\WebDev\Lullo\backend\node_modules\@ts-morph\common\dist\typescript.js:46218:31)
    at TypeChecker.getTypeAtLocation (E:\Documents\CODE\WebDev\Lullo\backend\node_modules\ts-morph\dist\ts-morph.js:17030:74)
    at ImportClause.getType (E:\Documents\CODE\WebDev\Lullo\backend\node_modules\ts-morph\dist\ts-morph.js:3085:42)
    at E:\Documents\CODE\WebDev\Lullo\backend\src\utils\TSC\test2.ts:29:28
    at nodeCallback (E:\Documents\CODE\WebDev\Lullo\backend\node_modules\ts-morph\dist\ts-morph.js:3253:33)
    at E:\Documents\CODE\WebDev\Lullo\backend\node_modules\ts-morph\dist\ts-morph.js:3288:37
    at ImportDeclaration.forEachChild (E:\Documents\CODE\WebDev\Lullo\backend\node_modules\ts-morph\dist\ts-morph.js:3233:37)
```


Does the `instrinsicName: 'error'` mean anything important?
Do I need to implement some kind of TypeGuard to use the `node.getType()` function?

Thanks

**UPDATE**

Seems commenting in an issue makes you find yourself in the docs. This helped me.
[/navigation/#traversal-control](https://ts-morph.com/navigation/#traversal-control)

Posting here for future reference
